name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.7
    - name: Install dependencies
      run: bundle install
    - name: Setup ENV
      run: cp .example.env .env.test
    - name: Lint
      run: bundle exec rubocop
    - name: Run tests
      run: bundle exec rspec
